In [1]:
import pandas as pd

In [11]:
import os

In [12]:
print(os.getcwd())

c:\Users\Jatin\OneDrive\Desktop\DL projects\ecom-ai\nlp

In [13]:
df = pd.read_csv(r"C:\Users\Jatin\OneDrive\Desktop\DL projects\ecom-ai\data\flipkart_product.csv", encoding="latin1")

In [14]:
df.head()

,ProductName,Price,Rate,Review,Summary
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Super!,Great cooler.. excellent air flow and for this...
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Awesome,Best budget 2 fit cooler. Nice cooling
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,The quality is good but the power of air is de...
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",1,Useless product,Very bad product it's a only a fan
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,Ok ok product

In [15]:
df.shape

(189874, 5)

In [16]:
df.columns.tolist()

['ProductName', 'Price', 'Rate', 'Review', 'Summary']

In [17]:
df.isnull().sum()

ProductName     0
Price           1
Rate            1
Review          4
Summary        14
dtype: int64

In [19]:
import matplotlib.pyplot as plt

In [21]:
df['Rate'].value_counts().sort_index()

Rate
1                                                               19607
2                                                                6234
3                                                               15681
4                                                               39653
5                                                              108694
Bajaj DX 2 L/W Dry Iron                                             1
Nova Plus Amaze NI 10 1100 W Dry Iron?ÿ?ÿ(Grey & Turquoise)         1
Pigeon Favourite Electric Kettle?ÿ?ÿ(1.5 L, Silver, Black)          1
s                                                                   1
Name: count, dtype: int64

In [22]:
df=df.dropna(subset=["Summary","Rate"])
df["Rate"]=pd.to_numeric(df["Rate"],errors="coerce")
df=df.dropna(subset=["Rate"])

C:\Users\Jatin\AppData\Local\Temp\ipykernel_29532\127267865.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Rate"]=pd.to_numeric(df["Rate"],errors="coerce")

In [23]:
df.isnull().sum()

ProductName    0
Price          0
Rate           0
Review         3
Summary        0
dtype: int64

In [24]:
df["sentiment"]=df["Rate"].apply(lambda x:"positive" if x>=4 else ('negative' if x<=2 else "neutral"))
df.head()

,ProductName,Price,Rate,Review,Summary,sentiment
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5.0,Super!,Great cooler.. excellent air flow and for this...,positive
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5.0,Awesome,Best budget 2 fit cooler. Nice cooling,positive
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3.0,Fair,The quality is good but the power of air is de...,neutral
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",1.0,Useless product,Very bad product it's a only a fan,negative
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3.0,Fair,Ok ok product,neutral

In [25]:
df['sentiment'].value_counts()

sentiment
positive    148335
negative     25841
neutral      15680
Name: count, dtype: int64

In [26]:
df.isnull().sum()

ProductName    0
Price          0
Rate           0
Review         3
Summary        0
sentiment      0
dtype: int64

In [27]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 4.6 MB/s eta 0:00:00
Installing collected packages: nltk
Successfully installed nltk-3.9.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
import nltk
import re

In [29]:
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jatin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jatin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [30]:
df = pd.read_csv(r"C:\Users\Jatin\OneDrive\Desktop\DL projects\ecom-ai\data\flipkart_product.csv", encoding="latin1")

In [31]:
stop_words = set(stopwords.words('english'))

In [32]:
def preprocess(text):
    # Lowercase
    text = text.lower()
    # Special characters remove
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Extra spaces remove
    text = re.sub(r'\s+', ' ', text).strip()
    # Stopwords remove
    tokens = text.split()
    tokens = [w for w in tokens if w not in stop_words]
    return ' '.join(tokens)

In [34]:
def preprocess(text):
    if not isinstance(text, str):
        return ''
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokens = text.split()
    tokens = [w for w in tokens if w not in stop_words]
    return ' '.join(tokens)

df['clean_summary'] = df['Summary'].apply(preprocess)

In [35]:
df = df[df['clean_summary'].str.len() > 0]

In [36]:
df.head()

,ProductName,Price,Rate,Review,Summary,clean_summary
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Super!,Great cooler.. excellent air flow and for this...,great cooler excellent air flow price amazing ...
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Awesome,Best budget 2 fit cooler. Nice cooling,best budget fit cooler nice cooling
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,The quality is good but the power of air is de...,quality good power air decent
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",1,Useless product,Very bad product it's a only a fan,bad product fan
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,Ok ok product,ok ok product

In [37]:
df.isnull().sum()

ProductName      0
Price            0
Rate             0
Review           3
Summary          0
clean_summary    0
dtype: int64

In [42]:
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce')
df = df.dropna(subset=['Rate'])
df['sentiment'] = df['Rate'].apply(lambda x: 'positive' if x >= 4 else ('negative' if x <= 2 else 'neutral'))

In [39]:
df.shape

(189797, 6)

In [43]:
df["sentiment"].value_counts()

sentiment
positive    148292
negative     25827
neutral      15674
Name: count, dtype: int64

In [44]:
df.isnull().sum()

ProductName      0
Price            0
Rate             0
Review           3
Summary          0
clean_summary    0
sentiment        0
dtype: int64

In [46]:
from sklearn.utils import resample

In [47]:
positive = df[df['sentiment'] == 'positive']
negative = df[df['sentiment'] == 'negative']
neutral = df[df['sentiment'] == 'neutral']

In [49]:
positive.shape

(148292, 7)

In [50]:
neutral.shape

(15674, 7)

In [51]:
#class imbalance handle

In [52]:
min_count=min(len(positive),len(negative),len(neutral)
              
              )

In [53]:
min_count

15674

In [54]:
positive_balanced = resample(positive, n_samples=min_count, random_state=42)
negative_balanced = resample(negative, n_samples=min_count, random_state=42)
neutral_balanced = resample(neutral, n_samples=min_count, random_state=42)

In [55]:
df_balanced = pd.concat([positive_balanced, negative_balanced, neutral_balanced])

In [57]:
df_balanced.shape

(47022, 7)

In [58]:
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

In [60]:
df_balanced

,ProductName,Price,Rate,Review,Summary,clean_summary,sentiment
0,HP 680 Black Ink Cartridge,??852,3.0,Decent product,Gud,gud,neutral
1,Google Nest Mini (2nd Gen) with Google Assista...,"??3,499",2.0,Bad quality,Downtime is on issues,downtime issues,negative
2,PHILIPS HR7627/00 650 W Food ProcessorÂ Â (White),"â¹4,319",1.0,Unsatisfactory,Ridiculous.. my return request was delayed and...,ridiculous return request delayed misguided le...,negative
3,ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...,"â¹58,990",1.0,Utterly Disappointed,Display not working yet,display working yet,negative
4,UPC Upgraded Hands Free Squeeze Microfiber Fla...,"â¹1,260",3.0,Just okay,Review after first use- I have a tiled floor a...,review first use tiled floor home decided get ...,neutral
...,...,...,...,...,...,...,...
47017,Men Graphic Print Round Neck Black T-Shirt,??269,4.0,Nan,Fantastic,fantastic,positive
47018,Canon PG 745S Black Ink Cartridge,??615,3.0,Decent product,Good,good,neutral
47019,CMerchants Multi Organiser BLue-4 Book Shelf M...,â¹625,3.0,Fair,Average product but very useful . Should buy w...,average product useful buy looks low price boo...,neutral
47020,Home Sizzler 153 cm (5.02 ft) Polyester Room D...,â¹299,5.0,Terrific,It's beautiful must buy it!!,beautiful must buy,positive
47021,HP 46 Black Ink Cartridge,??912,1.0,Don't waste your money,cartridge not recognised by printer,cartridge recognised printer,negative

In [61]:
print(df_balanced['sentiment'].value_counts())

sentiment
neutral     15674
negative    15674
positive    15674
Name: count, dtype: int64

In [62]:
pip install scikit-learn mlflow

Requirement already satisfied: scikit-learn in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (1.8.0)
Requirement already satisfied: mlflow in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (3.12.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: mlflow-skinny==3.12.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.12.0)
Requirement already satisfied: mlflow-tracing==3.12.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.12.0)
Requirement already satisfied: Flask-CORS<7 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (46.0.7)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<3,>=2.5.4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.10.9)
Requirement already satisfied: pandas<3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (23.0.1)
Requirement already satisfied: skops<1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (2.0.50)
Requirement already satisfied: waitress<4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (8.4.1)
Requirement already satisfied: cloudpickle<4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.111.0)
Requirement already satisfied: fastapi<1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (2.34.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.48.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from aiohttp<4->mlflow) (1.24.2)
Requirement already satisfied: Mako in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=2.0.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: pywin32>=304 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.7.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from matplotlib<4->mlflow) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: prettytable>=3.9 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.1)
Requirement already satisfied: pycparser in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: colorama in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.12.0->mlflow) (0.4.6)
Requirement already satisfied: google-auth~=2.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (2.53.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.12.0->mlflow) (4.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.12.0->mlflow) (0.63b1)
Requirement already satisfied: wcwidth in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.7.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.16)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (2026.5.20)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from starlette<1->mlflow-skinny==3.12.0->mlflow) (4.13.0)
Requirement already satisfied: h11>=0.8 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from uvicorn<1->mlflow-skinny==3.12.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (0.6.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
pip install transformers torch

Requirement already satisfied: transformers in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (5.9.0)
Requirement already satisfied: torch in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (2.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (1.16.4)
Requirement already satisfied: numpy>=1.17 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from torch) (2026.4.0)
Requirement already satisfied: click>=8.4.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.16)
Requirement already satisfied: h11>=0.16 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\jatin\onedrive\desktop\dl projects\ecom-ai\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:
""" from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import mlflow
import mlflow.sklearn

# Data split
X = df_balanced['clean_summary']
y = df_balanced['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2))
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# MLflow tracking
mlflow.set_experiment("Sentiment_Analysis")

with mlflow.start_run():
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train_tfidf, y_train)
    
    acc = model.score(X_test_tfidf, y_test)
    
    mlflow.log_param("model", "LogisticRegression")
    mlflow.log_param("max_features", 10000)
    mlflow.log_metric("accuracy", acc)
    mlflow.sklearn.log_model(model, "sentiment_model")
    
    print(f"Accuracy: {acc:.2f}")
    print("\nClassification Report:")
    print(classification_report(y_test, model.predict(X_test_tfidf))) """

' from sklearn.model_selection import train_test_split\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import classification_report\nimport mlflow\nimport mlflow.sklearn\n\n# Data split\nX = df_balanced[\'clean_summary\']\ny = df_balanced[\'sentiment\']\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# TF-IDF Vectorizer\ntfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2))\nX_train_tfidf = tfidf.fit_transform(X_train)\nX_test_tfidf = tfidf.transform(X_test)\n\n# MLflow tracking\nmlflow.set_experiment("Sentiment_Analysis")\n\nwith mlflow.start_run():\n    model = LogisticRegression(max_iter=1000)\n    model.fit(X_train_tfidf, y_train)\n\n    acc = model.score(X_test_tfidf, y_test)\n\n    mlflow.log_param("model", "LogisticRegression")\n    mlflow.log_param("max_features", 10000)\n    mlflow.log_metric("accuracy", acc)\n    mlflow.sklearn.log_model(model, "sentiment_model")\n\n    print(f"Accuracy: {acc:.2f}")\n    print("\nClassification Report:")\n    print(classification_report(y_test, model.predict(X_test_tfidf))) '